const likertOptions = () => [
  { key: 'A', text: 'Strongly Agree' },
  { key: 'B', text: 'Agree' },
  { key: 'C', text: 'Neutral' },
  { key: 'D', text: 'Disagree' },
  { key: 'E', text: 'Strongly Disagree' },
];

const personalityQuestions = [
  // EI
  {
    section: 'personality',
    category: 'personality',
    questionCode: 'P01',
    text: 'I feel energized after interacting with groups of people.',
    answerType: 'likert',
    options: likertOptions(),
    meta: { personality: { dimension: 'EI', targetPole: 'E' } },
  },
  {
    section: 'personality',
    category: 'personality',
    questionCode: 'P02',
    text: 'I prefer working independently rather than in teams.',
    answerType: 'likert',
    options: likertOptions(),
    meta: { personality: { dimension: 'EI', targetPole: 'I' } },
  },
  {
    section: 'personality',
    category: 'personality',
    questionCode: 'P03',
    text: 'I speak up quickly during meetings.',
    answerType: 'likert',
    options: likertOptions(),
    meta: { personality: { dimension: 'EI', targetPole: 'E' } },
  },
  {
    section: 'personality',
    category: 'personality',
    questionCode: 'P04',
    text: 'I need quiet time alone to recharge.',
    answerType: 'likert',
    options: likertOptions(),
    meta: { personality: { dimension: 'EI', targetPole: 'I' } },
  },
  {
    section: 'personality',
    category: 'personality',
    questionCode: 'P05',
    text: 'I actively seek networking opportunities.',
    answerType: 'likert',
    options: likertOptions(),
    meta: { personality: { dimension: 'EI', targetPole: 'E' } },
  },
  {
    section: 'personality',
    category: 'personality',
    questionCode: 'P06',
    text: 'I initiate conversations easily.',
    answerType: 'likert',
    options: likertOptions(),
    meta: { personality: { dimension: 'EI', targetPole: 'E' } },
  },
  {
    section: 'personality',
    category: 'personality',
    questionCode: 'P07',
    text: 'I feel mentally drained after social events.',
    answerType: 'likert',
    options: likertOptions(),
    meta: { personality: { dimension: 'EI', targetPole: 'I' } },
  },
  {
    section: 'personality',
    category: 'personality',
    questionCode: 'P08',
    text: 'I gain motivation from teamwork.',
    answerType: 'likert',
    options: likertOptions(),
    meta: { personality: { dimension: 'EI', targetPole: 'E' } },
  },

  // SN
  {
    section: 'personality',
    category: 'personality',
    questionCode: 'P09',
    text: 'I focus on concrete facts rather than abstract ideas.',
    answerType: 'likert',
    options: likertOptions(),
    meta: { personality: { dimension: 'SN', targetPole: 'S' } },
  },
  {
    section: 'personality',
    category: 'personality',
    questionCode: 'P10',
    text: 'I enjoy theoretical discussions.',
    answerType: 'likert',
    options: likertOptions(),
    meta: { personality: { dimension: 'SN', targetPole: 'N' } },
  },
  {
    section: 'personality',
    category: 'personality',
    questionCode: 'P11',
    text: 'I imagine future possibilities often.',
    answerType: 'likert',
    options: likertOptions(),
    meta: { personality: { dimension: 'SN', targetPole: 'N' } },
  },
  {
    section: 'personality',
    category: 'personality',
    questionCode: 'P12',
    text: 'I connect patterns between unrelated ideas.',
    answerType: 'likert',
    options: likertOptions(),
    meta: { personality: { dimension: 'SN', targetPole: 'N' } },
  },
  {
    section: 'personality',
    category: 'personality',
    questionCode: 'P13',
    text: 'I notice small factual details quickly.',
    answerType: 'likert',
    options: likertOptions(),
    meta: { personality: { dimension: 'SN', targetPole: 'S' } },
  },
  {
    section: 'personality',
    category: 'personality',
    questionCode: 'P14',
    text: 'I prefer step-by-step instructions.',
    answerType: 'likert',
    options: likertOptions(),
    meta: { personality: { dimension: 'SN', targetPole: 'S' } },
  },
  {
    section: 'personality',
    category: 'personality',
    questionCode: 'P15',
    text: 'I enjoy innovation and new methods.',
    answerType: 'likert',
    options: likertOptions(),
    meta: { personality: { dimension: 'SN', targetPole: 'N' } },
  },
  {
    section: 'personality',
    category: 'personality',
    questionCode: 'P16',
    text: 'I brainstorm alternative solutions frequently.',
    answerType: 'likert',
    options: likertOptions(),
    meta: { personality: { dimension: 'SN', targetPole: 'N' } },
  },

  // TF
  {
    section: 'personality',
    category: 'personality',
    questionCode: 'P17',
    text: 'I prioritize logic over emotions in decisions.',
    answerType: 'likert',
    options: likertOptions(),
    meta: { personality: { dimension: 'TF', targetPole: 'T' } },
  },
  {
    section: 'personality',
    category: 'personality',
    questionCode: 'P18',
    text: 'I consider others’ feelings before finalizing decisions.',
    answerType: 'likert',
    options: likertOptions(),
    meta: { personality: { dimension: 'TF', targetPole: 'F' } },
  },
  {
    section: 'personality',
    category: 'personality',
    questionCode: 'P19',
    text: 'I value fairness more than harmony.',
    answerType: 'likert',
    options: likertOptions(),
    meta: { personality: { dimension: 'TF', targetPole: 'T' } },
  },
  {
    section: 'personality',
    category: 'personality',
    questionCode: 'P20',
    text: 'I avoid conflict to preserve relationships.',
    answerType: 'likert',
    options: likertOptions(),
    meta: { personality: { dimension: 'TF', targetPole: 'F' } },
  },
  {
    section: 'personality',
    category: 'personality',
    questionCode: 'P21',
    text: 'I prefer objective evaluation.',
    answerType: 'likert',
    options: likertOptions(),
    meta: { personality: { dimension: 'TF', targetPole: 'T' } },
  },
  {
    section: 'personality',
    category: 'personality',
    questionCode: 'P22',
    text: 'I empathize easily with people’s struggles.',
    answerType: 'likert',
    options: likertOptions(),
    meta: { personality: { dimension: 'TF', targetPole: 'F' } },
  },
  {
    section: 'personality',
    category: 'personality',
    questionCode: 'P23',
    text: 'I openly challenge weak reasoning.',
    answerType: 'likert',
    options: likertOptions(),
    meta: { personality: { dimension: 'TF', targetPole: 'T' } },
  },
  {
    section: 'personality',
    category: 'personality',
    questionCode: 'P24',
    text: 'I aim for consensus in group decisions.',
    answerType: 'likert',
    options: likertOptions(),
    meta: { personality: { dimension: 'TF', targetPole: 'F' } },
  },

  // JP
  {
    section: 'personality',
    category: 'personality',
    questionCode: 'P25',
    text: 'I prefer structured plans before starting work.',
    answerType: 'likert',
    options: likertOptions(),
    meta: { personality: { dimension: 'JP', targetPole: 'J' } },
  },
  {
    section: 'personality',
    category: 'personality',
    questionCode: 'P26',
    text: 'I enjoy keeping options open.',
    answerType: 'likert',
    options: likertOptions(),
    meta: { personality: { dimension: 'JP', targetPole: 'P' } },
  },
  {
    section: 'personality',
    category: 'personality',
    questionCode: 'P27',
    text: 'I complete tasks ahead of schedule.',
    answerType: 'likert',
    options: likertOptions(),
    meta: { personality: { dimension: 'JP', targetPole: 'J' } },
  },
  {
    section: 'personality',
    category: 'personality',
    questionCode: 'P28',
    text: 'I adapt comfortably to sudden changes.',
    answerType: 'likert',
    options: likertOptions(),
    meta: { personality: { dimension: 'JP', targetPole: 'P' } },
  },
  {
    section: 'personality',
    category: 'personality',
    questionCode: 'P29',
    text: 'I prefer organized routines.',
    answerType: 'likert',
    options: likertOptions(),
    meta: { personality: { dimension: 'JP', targetPole: 'J' } },
  },
  {
    section: 'personality',
    category: 'personality',
    questionCode: 'P30',
    text: 'I enjoy spontaneity.',
    answerType: 'likert',
    options: likertOptions(),
    meta: { personality: { dimension: 'JP', targetPole: 'P' } },
  },
  {
    section: 'personality',
    category: 'personality',
    questionCode: 'P31',
    text: 'I delay decisions to gather more information.',
    answerType: 'likert',
    options: likertOptions(),
    meta: { personality: { dimension: 'JP', targetPole: 'P' } },
  },
  {
    section: 'personality',
    category: 'personality',
    questionCode: 'P32',
    text: 'I prefer closure once a decision is made.',
    answerType: 'likert',
    options: likertOptions(),
    meta: { personality: { dimension: 'JP', targetPole: 'J' } },
  },
];

const technicalQuestions = [
  // ---------------- CORE (T33 - T51) ----------------
  {
    section: 'technical',
    category: 'technical',
    questionCode: 'T33',
    text: 'Big-O notation is used to measure:',
    answerType: 'single',
    correctOptionIndex: 1,
    options: [
      { key: 'A', text: 'Code readability' },
      { key: 'B', text: 'Algorithm efficiency', isCorrect: true },
      { key: 'C', text: 'UI responsiveness' },
      { key: 'D', text: 'Server uptime' },
    ],
    meta: { technical: { area: 'core', isSpecialty: false, multiplier: 1.2 } },
  },
  {
    section: 'technical',
    category: 'technical',
    questionCode: 'T34',
    text: 'A primary key ensures:',
    answerType: 'single',
    correctOptionIndex: 1,
    options: [
      { key: 'A', text: 'Fast sorting' },
      { key: 'B', text: 'Unique identification', isCorrect: true },
      { key: 'C', text: 'Data backup' },
      { key: 'D', text: 'Encryption' },
    ],
    meta: { technical: { area: 'core', isSpecialty: false, multiplier: 1.2 } },
  },
  {
    section: 'technical',
    category: 'technical',
    questionCode: 'T35',
    text: 'REST APIs commonly use:',
    answerType: 'single',
    correctOptionIndex: 2,
    options: [
      { key: 'A', text: 'SMTP' },
      { key: 'B', text: 'FTP' },
      { key: 'C', text: 'HTTP', isCorrect: true },
      { key: 'D', text: 'SSH' },
    ],
    meta: { technical: { area: 'core', isSpecialty: false, multiplier: 1.2 } },
  },
  {
    section: 'technical',
    category: 'technical',
    questionCode: 'T36',
    text: 'Recursion refers to:',
    answerType: 'single',
    correctOptionIndex: 1,
    options: [
      { key: 'A', text: 'Nested loops' },
      { key: 'B', text: 'A function calling itself', isCorrect: true },
      { key: 'C', text: 'Parallel processing' },
      { key: 'D', text: 'Database indexing' },
    ],
    meta: { technical: { area: 'core', isSpecialty: false, multiplier: 1.2 } },
  },
  {
    section: 'technical',
    category: 'technical',
    questionCode: 'T37',
    text: 'An API is:',
    answerType: 'single',
    correctOptionIndex: 1,
    options: [
      { key: 'A', text: 'A user interface' },
      { key: 'B', text: 'A communication interface between systems', isCorrect: true },
      { key: 'C', text: 'A database engine' },
      { key: 'D', text: 'A programming language' },
    ],
    meta: { technical: { area: 'core', isSpecialty: false, multiplier: 1.2 } },
  },
  {
    section: 'technical',
    category: 'technical',
    questionCode: 'T38',
    text: 'The DOM represents:',
    answerType: 'single',
    correctOptionIndex: 1,
    options: [
      { key: 'A', text: 'Database Object Model' },
      { key: 'B', text: 'Document Object Model', isCorrect: true },
      { key: 'C', text: 'Data Operation Mode' },
      { key: 'D', text: 'Design Object Mapping' },
    ],
    meta: { technical: { area: 'core', isSpecialty: false, multiplier: 1.0 } },
  },
  {
    section: 'technical',
    category: 'technical',
    questionCode: 'T39',
    text: 'CSS Flexbox is primarily used for:',
    answerType: 'single',
    correctOptionIndex: 1,
    options: [
      { key: 'A', text: 'Animations' },
      { key: 'B', text: 'Layout alignment', isCorrect: true },
      { key: 'C', text: 'Security' },
      { key: 'D', text: 'Backend routing' },
    ],
    meta: { technical: { area: 'core', isSpecialty: false, multiplier: 1.0 } },
  },
  {
    section: 'technical',
    category: 'technical',
    questionCode: 'T40',
    text: 'Media queries are used for:',
    answerType: 'single',
    correctOptionIndex: 1,
    options: [
      { key: 'A', text: 'Security rules' },
      { key: 'B', text: 'Responsive design', isCorrect: true },
      { key: 'C', text: 'Database queries' },
      { key: 'D', text: 'API calls' },
    ],
    meta: { technical: { area: 'core', isSpecialty: false, multiplier: 1.0 } },
  },
  {
    section: 'technical',
    category: 'technical',
    questionCode: 'T41',
    text: 'Accessibility (a11y) ensures:',
    answerType: 'single',
    correctOptionIndex: 1,
    options: [
      { key: 'A', text: 'Fast loading' },
      { key: 'B', text: 'Usability for all users', isCorrect: true },
      { key: 'C', text: 'SEO ranking' },
      { key: 'D', text: 'Encryption' },
    ],
    meta: { technical: { area: 'core', isSpecialty: false, multiplier: 1.0 } },
  },
  {
    section: 'technical',
    category: 'technical',
    questionCode: 'T42',
    text: 'Middleware is used to:',
    answerType: 'single',
    correctOptionIndex: 1,
    options: [
      { key: 'A', text: 'Design UI' },
      { key: 'B', text: 'Process requests between client and server', isCorrect: true },
      { key: 'C', text: 'Store passwords' },
      { key: 'D', text: 'Compile code' },
    ],
    meta: { technical: { area: 'core', isSpecialty: false, multiplier: 1.0 } },
  },
  {
    section: 'technical',
    category: 'technical',
    questionCode: 'T43',
    text: 'JWT is used for:',
    answerType: 'single',
    correctOptionIndex: 1,
    options: [
      { key: 'A', text: 'Styling' },
      { key: 'B', text: 'Authentication', isCorrect: true },
      { key: 'C', text: 'Logging' },
      { key: 'D', text: 'Caching' },
    ],
    meta: { technical: { area: 'core', isSpecialty: false, multiplier: 1.0 } },
  },
  {
    section: 'technical',
    category: 'technical',
    questionCode: 'T44',
    text: 'ACID properties relate to:',
    answerType: 'single',
    correctOptionIndex: 1,
    options: [
      { key: 'A', text: 'Networking' },
      { key: 'B', text: 'Database transactions', isCorrect: true },
      { key: 'C', text: 'UI components' },
      { key: 'D', text: 'Encryption' },
    ],
    meta: { technical: { area: 'core', isSpecialty: false, multiplier: 1.0 } },
  },
  {
    section: 'technical',
    category: 'technical',
    questionCode: 'T45',
    text: 'Caching improves:',
    answerType: 'single',
    correctOptionIndex: 1,
    options: [
      { key: 'A', text: 'Security' },
      { key: 'B', text: 'Performance', isCorrect: true },
      { key: 'C', text: 'Compilation' },
      { key: 'D', text: 'Logging' },
    ],
    meta: { technical: { area: 'core', isSpecialty: false, multiplier: 1.0 } },
  },
  {
    section: 'technical',
    category: 'technical',
    questionCode: 'T46',
    text: 'Microservices architecture divides systems into:',
    answerType: 'single',
    correctOptionIndex: 1,
    options: [
      { key: 'A', text: 'UI components' },
      { key: 'B', text: 'Independent services', isCorrect: true },
      { key: 'C', text: 'Single database' },
      { key: 'D', text: 'Static files' },
    ],
    meta: { technical: { area: 'core', isSpecialty: false, multiplier: 1.0 } },
  },
  {
    section: 'technical',
    category: 'technical',
    questionCode: 'T47',
    text: 'Overfitting occurs when:',
    answerType: 'single',
    correctOptionIndex: 1,
    options: [
      { key: 'A', text: 'Model generalizes well' },
      { key: 'B', text: 'Model memorizes training data', isCorrect: true },
      { key: 'C', text: 'Data is clean' },
      { key: 'D', text: 'Algorithm fails' },
    ],
    meta: { technical: { area: 'core', isSpecialty: false, multiplier: 1.0 } },
  },
  {
    section: 'technical',
    category: 'technical',
    questionCode: 'T48',
    text: 'Regression is used for:',
    answerType: 'single',
    correctOptionIndex: 1,
    options: [
      { key: 'A', text: 'Classification' },
      { key: 'B', text: 'Predicting continuous values', isCorrect: true },
      { key: 'C', text: 'Clustering' },
      { key: 'D', text: 'Encryption' },
    ],
    meta: { technical: { area: 'core', isSpecialty: false, multiplier: 1.0 } },
  },
  {
    section: 'technical',
    category: 'technical',
    questionCode: 'T49',
    text: 'Cross-validation is used to:',
    answerType: 'single',
    correctOptionIndex: 1,
    options: [
      { key: 'A', text: 'Increase dataset' },
      { key: 'B', text: 'Validate model performance', isCorrect: true },
      { key: 'C', text: 'Remove bias' },
      { key: 'D', text: 'Encrypt data' },
    ],
    meta: { technical: { area: 'core', isSpecialty: false, multiplier: 1.0 } },
  },
  {
    section: 'technical',
    category: 'technical',
    questionCode: 'T50',
    text: 'SQL JOIN is used to:',
    answerType: 'single',
    correctOptionIndex: 1,
    options: [
      { key: 'A', text: 'Delete records' },
      { key: 'B', text: 'Combine tables', isCorrect: true },
      { key: 'C', text: 'Encrypt database' },
      { key: 'D', text: 'Sort data' },
    ],
    meta: { technical: { area: 'core', isSpecialty: false, multiplier: 1.0 } },
  },
  {
    section: 'technical',
    category: 'technical',
    questionCode: 'T51',
    text: 'Standard deviation measures:',
    answerType: 'single',
    correctOptionIndex: 1,
    options: [
      { key: 'A', text: 'Accuracy' },
      { key: 'B', text: 'Data spread', isCorrect: true },
      { key: 'C', text: 'Median' },
      { key: 'D', text: 'Mode' },
    ],
    meta: { technical: { area: 'core', isSpecialty: false, multiplier: 1.0 } },
  },

  // ---------------- SPECIALTY: WEB ----------------
  {
    section: 'technical',
    category: 'technical',
    questionCode: 'TS-WEB-01',
    text: 'What does the DOM represent?',
    answerType: 'single',
    correctOptionIndex: 1,
    options: [
      { key: 'A', text: 'Database Object Model' },
      { key: 'B', text: 'Document Object Model', isCorrect: true },
      { key: 'C', text: 'Data Operation Mode' },
      { key: 'D', text: 'Design Object Mapping' },
    ],
    meta: {
      technical: {
        area: 'concept',
        interest: 'web',
        isSpecialty: true,
        multiplier: 1.15,
      },
    },
  },
  {
    section: 'technical',
    category: 'technical',
    questionCode: 'TS-WEB-02',
    text: 'CSS Flexbox is primarily used for:',
    answerType: 'single',
    correctOptionIndex: 1,
    options: [
      { key: 'A', text: 'Animations' },
      { key: 'B', text: 'Layout alignment', isCorrect: true },
      { key: 'C', text: 'Security' },
      { key: 'D', text: 'Backend routing' },
    ],
    meta: {
      technical: {
        area: 'tool',
        interest: 'web',
        isSpecialty: true,
        multiplier: 1.15,
      },
    },
  },
  {
    section: 'technical',
    category: 'technical',
    questionCode: 'TS-WEB-03',
    text: 'Media queries are mainly used to:',
    answerType: 'single',
    correctOptionIndex: 1,
    options: [
      { key: 'A', text: 'Secure APIs' },
      { key: 'B', text: 'Build responsive layouts for different screen sizes', isCorrect: true },
      { key: 'C', text: 'Connect databases' },
      { key: 'D', text: 'Improve server-side caching' },
    ],
    meta: {
      technical: {
        area: 'applied',
        interest: 'web',
        isSpecialty: true,
        multiplier: 1.2,
      },
    },
  },

  // ---------------- SPECIALTY: DATA / AI ----------------
  {
    section: 'technical',
    category: 'technical',
    questionCode: 'TS-DATA-01',
    text: 'Overfitting occurs when:',
    answerType: 'single',
    correctOptionIndex: 1,
    options: [
      { key: 'A', text: 'A model generalizes well to unseen data' },
      { key: 'B', text: 'A model memorizes training data and performs poorly on new data', isCorrect: true },
      { key: 'C', text: 'The dataset is fully cleaned' },
      { key: 'D', text: 'The algorithm runs too slowly' },
    ],
    meta: {
      technical: {
        area: 'concept',
        interest: 'data_ai',
        isSpecialty: true,
        multiplier: 1.15,
      },
    },
  },
  {
    section: 'technical',
    category: 'technical',
    questionCode: 'TS-DATA-02',
    text: 'SQL JOIN is used to:',
    answerType: 'single',
    correctOptionIndex: 1,
    options: [
      { key: 'A', text: 'Delete records permanently' },
      { key: 'B', text: 'Combine data from multiple tables', isCorrect: true },
      { key: 'C', text: 'Encrypt database tables' },
      { key: 'D', text: 'Sort numeric columns only' },
    ],
    meta: {
      technical: {
        area: 'tool',
        interest: 'data_ai',
        isSpecialty: true,
        multiplier: 1.15,
      },
    },
  },
  {
    section: 'technical',
    category: 'technical',
    questionCode: 'TS-DATA-03',
    text: 'Cross-validation is mainly used to:',
    answerType: 'single',
    correctOptionIndex: 1,
    options: [
      { key: 'A', text: 'Increase dataset size' },
      { key: 'B', text: 'Evaluate how well a model may perform on unseen data', isCorrect: true },
      { key: 'C', text: 'Remove all bias from data' },
      { key: 'D', text: 'Replace test datasets completely' },
    ],
    meta: {
      technical: {
        area: 'applied',
        interest: 'data_ai',
        isSpecialty: true,
        multiplier: 1.2,
      },
    },
  },

  // ---------------- SPECIALTY: SECURITY ----------------
  {
    section: 'technical',
    category: 'technical',
    questionCode: 'TS-SEC-01',
    text: 'Phishing is best described as:',
    answerType: 'single',
    correctOptionIndex: 1,
    options: [
      { key: 'A', text: 'A type of database indexing' },
      { key: 'B', text: 'A social engineering attack used to steal information', isCorrect: true },
      { key: 'C', text: 'A method for encrypting files' },
      { key: 'D', text: 'A browser rendering issue' },
    ],
    meta: {
      technical: {
        area: 'concept',
        interest: 'security',
        isSpecialty: true,
        multiplier: 1.15,
      },
    },
  },
  {
    section: 'technical',
    category: 'technical',
    questionCode: 'TS-SEC-02',
    text: 'A firewall is primarily used to:',
    answerType: 'single',
    correctOptionIndex: 1,
    options: [
      { key: 'A', text: 'Create UI layouts' },
      { key: 'B', text: 'Filter and control network traffic', isCorrect: true },
      { key: 'C', text: 'Compress application files' },
      { key: 'D', text: 'Generate API documentation' },
    ],
    meta: {
      technical: {
        area: 'tool',
        interest: 'security',
        isSpecialty: true,
        multiplier: 1.15,
      },
    },
  },
  {
    section: 'technical',
    category: 'technical',
    questionCode: 'TS-SEC-03',
    text: 'Penetration testing is performed to:',
    answerType: 'single',
    correctOptionIndex: 1,
    options: [
      { key: 'A', text: 'Improve visual design consistency' },
      { key: 'B', text: 'Identify vulnerabilities before attackers exploit them', isCorrect: true },
      { key: 'C', text: 'Increase server storage capacity' },
      { key: 'D', text: 'Replace monitoring systems' },
    ],
    meta: {
      technical: {
        area: 'applied',
        interest: 'security',
        isSpecialty: true,
        multiplier: 1.2,
      },
    },
  },

  // ---------------- SPECIALTY: DESIGN ----------------
  {
    section: 'technical',
    category: 'technical',
    questionCode: 'TS-DESIGN-01',
    text: 'A wireframe is:',
    answerType: 'single',
    correctOptionIndex: 1,
    options: [
      { key: 'A', text: 'A final high-fidelity user interface' },
      { key: 'B', text: 'A low-fidelity layout used to plan structure', isCorrect: true },
      { key: 'C', text: 'A database relationship diagram' },
      { key: 'D', text: 'A backend deployment plan' },
    ],
    meta: {
      technical: {
        area: 'concept',
        interest: 'design',
        isSpecialty: true,
        multiplier: 1.15,
      },
    },
  },
  {
    section: 'technical',
    category: 'technical',
    questionCode: 'TS-DESIGN-02',
    text: 'Usability testing is used to evaluate:',
    answerType: 'single',
    correctOptionIndex: 1,
    options: [
      { key: 'A', text: 'Server uptime' },
      { key: 'B', text: 'How easily users can use a product/interface', isCorrect: true },
      { key: 'C', text: 'Encryption strength' },
      { key: 'D', text: 'Database performance' },
    ],
    meta: {
      technical: {
        area: 'tool',
        interest: 'design',
        isSpecialty: true,
        multiplier: 1.15,
      },
    },
  },
  {
    section: 'technical',
    category: 'technical',
    questionCode: 'TS-DESIGN-03',
    text: 'A user journey map is mainly used to:',
    answerType: 'single',
    correctOptionIndex: 1,
    options: [
      { key: 'A', text: 'Track network packets' },
      { key: 'B', text: 'Visualize the user’s steps and experience across interactions', isCorrect: true },
      { key: 'C', text: 'Define API endpoints' },
      { key: 'D', text: 'Build CSS themes' },
    ],
    meta: {
      technical: {
        area: 'applied',
        interest: 'design',
        isSpecialty: true,
        multiplier: 1.2,
      },
    },
  },

  // ---------------- SPECIALTY: PRODUCT ----------------
  {
    section: 'technical',
    category: 'technical',
    questionCode: 'TS-PRODUCT-01',
    text: 'What does MVP stand for?',
    answerType: 'single',
    correctOptionIndex: 1,
    options: [
      { key: 'A', text: 'Most Valuable Process' },
      { key: 'B', text: 'Minimum Viable Product', isCorrect: true },
      { key: 'C', text: 'Main Version Prototype' },
      { key: 'D', text: 'Managed Value Platform' },
    ],
    meta: {
      technical: {
        area: 'concept',
        interest: 'product',
        isSpecialty: true,
        multiplier: 1.15,
      },
    },
  },
  {
    section: 'technical',
    category: 'technical',
    questionCode: 'TS-PRODUCT-02',
    text: 'User stories are primarily used to describe:',
    answerType: 'single',
    correctOptionIndex: 1,
    options: [
      { key: 'A', text: 'Database schema rules' },
      { key: 'B', text: 'User needs and functional requirements', isCorrect: true },
      { key: 'C', text: 'Backend server configurations' },
      { key: 'D', text: 'Code refactoring steps' },
    ],
    meta: {
      technical: {
        area: 'tool',
        interest: 'product',
        isSpecialty: true,
        multiplier: 1.15,
      },
    },
  },
  {
    section: 'technical',
    category: 'technical',
    questionCode: 'TS-PRODUCT-03',
    text: 'A/B testing is typically used to:',
    answerType: 'single',
    correctOptionIndex: 0,
    options: [
      { key: 'A', text: 'Compare two product versions to measure performance or user response', isCorrect: true },
      { key: 'B', text: 'Encrypt user data' },
      { key: 'C', text: 'Increase server memory' },
      { key: 'D', text: 'Merge database tables' },
    ],
    meta: {
      technical: {
        area: 'applied',
        interest: 'product',
        isSpecialty: true,
        multiplier: 1.2,
      },
    },
  },

  // ---------------- SPECIALTY: DEVOPS ----------------
  {
    section: 'technical',
    category: 'technical',
    questionCode: 'TS-DEVOPS-01',
    text: 'Infrastructure as Code (IaC) means:',
    answerType: 'single',
    correctOptionIndex: 1,
    options: [
      { key: 'A', text: 'Designing UI components with code' },
      { key: 'B', text: 'Managing infrastructure using code/configuration files', isCorrect: true },
      { key: 'C', text: 'Writing database queries in JSON' },
      { key: 'D', text: 'Encrypting network traffic automatically' },
    ],
    meta: {
      technical: {
        area: 'concept',
        interest: 'devops',
        isSpecialty: true,
        multiplier: 1.15,
      },
    },
  },
  {
    section: 'technical',
    category: 'technical',
    questionCode: 'TS-DEVOPS-02',
    text: 'Kubernetes is primarily used for:',
    answerType: 'single',
    correctOptionIndex: 1,
    options: [
      { key: 'A', text: 'UI testing' },
      { key: 'B', text: 'Container orchestration', isCorrect: true },
      { key: 'C', text: 'Spreadsheet analysis' },
      { key: 'D', text: 'Browser automation' },
    ],
    meta: {
      technical: {
        area: 'tool',
        interest: 'devops',
        isSpecialty: true,
        multiplier: 1.15,
      },
    },
  },
  {
    section: 'technical',
    category: 'technical',
    questionCode: 'TS-DEVOPS-03',
    text: 'Blue-Green deployment is mainly used to:',
    answerType: 'single',
    correctOptionIndex: 1,
    options: [
      { key: 'A', text: 'Improve frontend color themes' },
      { key: 'B', text: 'Reduce downtime and deployment risk during releases', isCorrect: true },
      { key: 'C', text: 'Encrypt production logs' },
      { key: 'D', text: 'Replace monitoring tools' },
    ],
    meta: {
      technical: {
        area: 'applied',
        interest: 'devops',
        isSpecialty: true,
        multiplier: 1.2,
      },
    },
  },

  // ---------------- SPECIALTY: QA ----------------
  {
    section: 'technical',
    category: 'technical',
    questionCode: 'TS-QA-01',
    text: 'Unit testing is used to verify:',
    answerType: 'single',
    correctOptionIndex: 1,
    options: [
      { key: 'A', text: 'Entire end-to-end system behavior only' },
      { key: 'B', text: 'Individual functions/components in isolation', isCorrect: true },
      { key: 'C', text: 'UI colors and branding' },
      { key: 'D', text: 'Network bandwidth usage' },
    ],
    meta: {
      technical: {
        area: 'concept',
        interest: 'qa',
        isSpecialty: true,
        multiplier: 1.15,
      },
    },
  },
  {
    section: 'technical',
    category: 'technical',
    questionCode: 'TS-QA-02',
    text: 'A test case usually includes:',
    answerType: 'single',
    correctOptionIndex: 1,
    options: [
      { key: 'A', text: 'Only a bug title' },
      { key: 'B', text: 'Steps, inputs, and expected results', isCorrect: true },
      { key: 'C', text: 'Server credentials' },
      { key: 'D', text: 'API encryption keys' },
    ],
    meta: {
      technical: {
        area: 'tool',
        interest: 'qa',
        isSpecialty: true,
        multiplier: 1.15,
      },
    },
  },
  {
    section: 'technical',
    category: 'technical',
    questionCode: 'TS-QA-03',
    text: 'Regression testing is performed to:',
    answerType: 'single',
    correctOptionIndex: 0,
    options: [
      { key: 'A', text: 'Confirm existing features still work after changes', isCorrect: true },
      { key: 'B', text: 'Increase application speed' },
      { key: 'C', text: 'Create new UI layouts' },
      { key: 'D', text: 'Reduce database size' },
    ],
    meta: {
      technical: {
        area: 'applied',
        interest: 'qa',
        isSpecialty: true,
        multiplier: 1.2,
      },
    },
  },

  // ---------------- SPECIALTY: MOBILE / GAME ----------------
  {
    section: 'technical',
    category: 'technical',
    questionCode: 'TS-MOBILE-01',
    text: 'A game engine is primarily used to:',
    answerType: 'single',
    correctOptionIndex: 1,
    options: [
      { key: 'A', text: 'Store relational data' },
      { key: 'B', text: 'Build, render, and run game logic', isCorrect: true },
      { key: 'C', text: 'Encrypt user sessions' },
      { key: 'D', text: 'Test REST APIs' },
    ],
    meta: {
      technical: {
        area: 'concept',
        interest: 'mobile_game',
        isSpecialty: true,
        multiplier: 1.15,
      },
    },
  },
  {
    section: 'technical',
    category: 'technical',
    questionCode: 'TS-MOBILE-02',
    text: 'A physics engine in games typically handles:',
    answerType: 'single',
    correctOptionIndex: 1,
    options: [
      { key: 'A', text: 'Text styling' },
      { key: 'B', text: 'Movement, collision, and physical interactions', isCorrect: true },
      { key: 'C', text: 'Database replication' },
      { key: 'D', text: 'Cloud deployment' },
    ],
    meta: {
      technical: {
        area: 'tool',
        interest: 'mobile_game',
        isSpecialty: true,
        multiplier: 1.15,
      },
    },
  },
  {
    section: 'technical',
    category: 'technical',
    questionCode: 'TS-MOBILE-03',
    text: 'Multiplayer games require network synchronization mainly to:',
    answerType: 'single',
    correctOptionIndex: 1,
    options: [
      { key: 'A', text: 'Improve local UI colors' },
      { key: 'B', text: 'Keep game state consistent across players', isCorrect: true },
      { key: 'C', text: 'Replace game assets' },
      { key: 'D', text: 'Reduce frame rate' },
    ],
    meta: {
      technical: {
        area: 'applied',
        interest: 'mobile_game',
        isSpecialty: true,
        multiplier: 1.2,
      },
    },
  },
];
const softLikertOptions = () => [
  { key: 'A', text: 'Strongly Agree' },
  { key: 'B', text: 'Agree' },
  { key: 'C', text: 'Neutral' },
  { key: 'D', text: 'Disagree' },
  { key: 'E', text: 'Strongly Disagree' },
];

const softSingleOptions = (a, b, c, d) => [
  { key: 'A', text: a },
  { key: 'B', text: b },
  { key: 'C', text: c },
  { key: 'D', text: d },
];

const softSkillQuestions = [
  // ---------------- SOFT LIKERT (S61 - S68) ----------------
  {
    section: 'soft',
    category: 'soft',
    questionCode: 'S61',
    text: 'I manage my time effectively.',
    answerType: 'likert',
    options: softLikertOptions(),
    meta: {
      soft: {
        softType: 'likert',
        softCategory: 'self_management',
        isReverse: false,
      },
    },
  },
  {
    section: 'soft',
    category: 'soft',
    questionCode: 'S62',
    text: 'I frequently miss deadlines.',
    answerType: 'likert',
    options: softLikertOptions(),
    meta: {
      soft: {
        softType: 'likert',
        softCategory: 'self_management',
        isReverse: true,
      },
    },
  },
  {
    section: 'soft',
    category: 'soft',
    questionCode: 'S63',
    text: 'I handle stress well.',
    answerType: 'likert',
    options: softLikertOptions(),
    meta: {
      soft: {
        softType: 'likert',
        softCategory: 'adaptability',
        isReverse: false,
      },
    },
  },
  {
    section: 'soft',
    category: 'soft',
    questionCode: 'S64',
    text: 'I panic under pressure.',
    answerType: 'likert',
    options: softLikertOptions(),
    meta: {
      soft: {
        softType: 'likert',
        softCategory: 'adaptability',
        isReverse: true,
      },
    },
  },
  {
    section: 'soft',
    category: 'soft',
    questionCode: 'S65',
    text: 'I communicate clearly.',
    answerType: 'likert',
    options: softLikertOptions(),
    meta: {
      soft: {
        softType: 'likert',
        softCategory: 'communication',
        isReverse: false,
      },
    },
  },
  {
    section: 'soft',
    category: 'soft',
    questionCode: 'S66',
    text: 'I often misunderstand instructions.',
    answerType: 'likert',
    options: softLikertOptions(),
    meta: {
      soft: {
        softType: 'likert',
        softCategory: 'communication',
        isReverse: true,
      },
    },
  },
  {
    section: 'soft',
    category: 'soft',
    questionCode: 'S67',
    text: 'I take initiative.',
    answerType: 'likert',
    options: softLikertOptions(),
    meta: {
      soft: {
        softType: 'likert',
        softCategory: 'leadership',
        isReverse: false,
      },
    },
  },
  {
    section: 'soft',
    category: 'soft',
    questionCode: 'S68',
    text: 'I wait for instructions before acting.',
    answerType: 'likert',
    options: softLikertOptions(),
    meta: {
      soft: {
        softType: 'likert',
        softCategory: 'leadership',
        isReverse: true,
      },
    },
  },

  // ---------------- BEHAVIOR MCQ (S69 - S74) ----------------
  {
    section: 'soft',
    category: 'soft',
    questionCode: 'S69',
    text: 'When explaining a complex idea to a team, I:',
    answerType: 'single',
    options: softSingleOptions(
      'Break it into simple parts and check understanding',
      'Explain quickly and assume they understand',
      'Give written instructions only',
      'Avoid explaining and let them figure it out'
    ),
    meta: {
      soft: {
        softType: 'behavior',
        softCategory: 'communication',
        isReverse: false,
      },
    },
  },
  {
    section: 'soft',
    category: 'soft',
    questionCode: 'S70',
    text: 'In a group project, I usually:',
    answerType: 'single',
    options: softSingleOptions(
      'Offer help to teammates who are struggling',
      'Focus only on my assigned tasks',
      'Take over tasks from others without asking',
      'Avoid collaboration as much as possible'
    ),
    meta: {
      soft: {
        softType: 'behavior',
        softCategory: 'teamwork',
        isReverse: false,
      },
    },
  },
  {
    section: 'soft',
    category: 'soft',
    questionCode: 'S71',
    text: 'When project requirements suddenly change, I:',
    answerType: 'single',
    options: softSingleOptions(
      'Adjust plans quickly and continue',
      'Complain about the change',
      'Wait for someone else to decide what to do',
      'Stop working until direction is clear'
    ),
    meta: {
      soft: {
        softType: 'behavior',
        softCategory: 'adaptability',
        isReverse: false,
      },
    },
  },
  {
    section: 'soft',
    category: 'soft',
    questionCode: 'S72',
    text: 'When encountering a technical problem I do not know, I:',
    answerType: 'single',
    options: softSingleOptions(
      'Research and try multiple solutions',
      'Ask someone else to solve it immediately',
      'Ignore it and continue with other work',
      'Document the problem and wait without trying'
    ),
    meta: {
      soft: {
        softType: 'behavior',
        softCategory: 'problem_solving',
        isReverse: false,
      },
    },
  },
  {
    section: 'soft',
    category: 'soft',
    questionCode: 'S73',
    text: 'If a teammate is demotivated, I:',
    answerType: 'single',
    options: softSingleOptions(
      'Encourage them and offer guidance',
      'Leave them to handle it alone',
      'Complain to management about them',
      'Take over their tasks without discussion'
    ),
    meta: {
      soft: {
        softType: 'behavior',
        softCategory: 'leadership',
        isReverse: false,
      },
    },
  },
  {
    section: 'soft',
    category: 'soft',
    questionCode: 'S74',
    text: 'When I have multiple deadlines, I:',
    answerType: 'single',
    options: softSingleOptions(
      'Prioritize tasks and plan my time efficiently',
      'Work on whichever task I feel like first',
      'Rush everything at the last minute',
      'Delegate all tasks whenever possible'
    ),
    meta: {
      soft: {
        softType: 'behavior',
        softCategory: 'self_management',
        isReverse: false,
      },
    },
  },

  // ---------------- SJT (S75) ----------------
  {
    section: 'soft',
    category: 'soft',
    questionCode: 'S75',
    text: 'A conflict arises between team members. You:',
    answerType: 'single',
    options: softSingleOptions(
      'Stay out of it completely',
      'Mediate professionally and help clarify the issue',
      'Escalate immediately without discussion',
      'Take sides based on who seems stronger'
    ),
    meta: {
      soft: {
        softType: 'sjt',
        softCategory: 'teamwork',
        isReverse: false,
      },
    },
  },
];

module.exports = {
  personalityQuestions,
  technicalQuestions,
  softSkillQuestions,
};